#!/bin/sh

# Helper for running (and building) uninstalled code

topdir=$(dirname $0)
case $topdir in
	/*) ;;
	*) topdir=$(pwd)/$topdir ;;
esac

make=no
pixisim=no

while test $# -gt 0; do
	case $1 in
		-r|--release)
			echo release mode >&2
			BUILD_MODE=release
			;;
		-d|--debug)
			echo debug mode >&2
			BUILD_MODE=debug
			;;
		-s|--sim)
			echo enable simulator >&2
			pixisim=yes
			;;
		-p|--python)
			shift
			export PYTHON_VERSION=$1
			;;
		-m|--make)
			make=yes
			;;
		-*)
			echo "Unknown option: $1" >&2
			exit 1
			;;
		*)
			# no more options
			break
			;;
	esac
	shift
done

if test -z "$BUILD_MODE"; then
	BUILD_MODE=debug
fi

make_BM="BUILD_MODE=$BUILD_MODE"

mode=$BUILD_MODE$PYTHON_VERSION
builddir=$topdir/build/$mode

if test -z "$PYTHON_VERSION"; then
	PYTHON_VERSION=$(cd $topdir && make print-python-version)
else
	make_PY="PYTHON_VERSION=$PYTHON_VERSION"
fi

export LD_LIBRARY_PATH=$builddir/lib
PATH=$builddir/bin:$PATH
export PYTHONPATH=$builddir/lib/python$PYTHON_VERSION/site-packages

if test $make = yes; then
	make -C $topdir $make_BM $make_PY all temp-install
fi

if test $pixisim = yes; then
	export LD_PRELOAD=pixisim.so
fi

set -x
exec "$@"
