#!/usr/bin/env python

from __future__ import print_function

import sys
from pixitools.pixi import openPixi
from pixitools.rover import *
from time import sleep

def demo (speed = 100):
	def rest():
		sleep (3)
	moveForward (speed)
	rest()
	moveBackward (speed)
	rest()
	turnLeft (speed)
	rest()
	turnRight (speed)
	rest()

def run():
	commands = {
		'forward' : moveForward,
		'backward': moveBackward,
		'left'    : turnLeft,
		'right'   : turnRight
		}

	if len (sys.argv) == 2:
		if sys.argv[1] == "demo":
			enableMotor()
			demo()
		sys.exit (0)
	elif len (sys.argv) == 3:
		cmd = sys.argv[1]
		speed = int (sys.argv[2])
		try:
			speedL = int (cmd)
			speedR = speed
			enableMotor()
			moveRoverX (speedL, speedR)
			sleep (2)
			sys.exit(0)
		except ValueError:
			# cmd is not an int
			pass
		command = None
		for direction, function in commands.items():
			# allow direction to be 1 character or more:
			if direction.startswith (cmd):
				command = function
				break
		if command:
			enableMotor()
			command (speed)
			sleep (2)
			sys.exit (0)

	print ("usage: %s demo" % sys.argv[0])
	print ("usage: %s f[orward]|b[ackward]|l[eft]|r[ight] speed" % sys.argv[0])
	print ("usage: %s speed-L speed-R" % sys.argv[0])
	sys.exit (1)

openPixi()
try:
	run()
finally:
	enableMotor (False)
