#!/usr/bin/env python

#    pixi-tools: a set of software to interface with the Raspberry Pi
#    and PiXi-200 hardware
#    Copyright (C) 2013 Simon Cantrill
#
#    pixi-tools is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


from __future__ import print_function
from pixitools import pixix
from pixitools.pi import getLibVersion
from pixitools.pixi import openPixi, registerWrite
from time import sleep

openPixi()
lcd = pixix.Lcd()
echo = lcd.echo

lcd.clear()
lcd.setBrightness (0)

echo ("libpixi version " + getLibVersion())
echo ("pixi-demo")

for n in range (3, 0, -1):
	sleep (0.1)
	lcd.setBrightness (n)

for n in range (3):
	sleep (0.1)
	lcd.setBrightness (n)

def servo (address):
	return lambda value: registerWrite (address, value)

class Servo (object):
	def __init__ (self, address, values = [50, 52]):
		self.move = lambda value: registerWrite (address, value)
		self.address = address
		self.index  = 0
		self.values = values
		self.toggle()

	def toggle (self):
		index = self.index
		self.index = not index
		value = self.values[index]
		echo ("Setting %d to %d" % (self.address, value))
		self.move (value)

def servos():
	# setter, toggle, low, high
	a1 = Servo (pixix.ServoA1, [50, 70])
	a2 = Servo (pixix.ServoA2)
	b1 = Servo (pixix.ServoB1)
	b2 = Servo (pixix.ServoB2)

	all = a1, a2, b1, b2

	for n in range (2):
		sleep (2)
		for srv in all:
			srv.toggle()
			sleep (1)

#servos()
