#!/usr/bin/env python

#    pixi-tools: a set of software to interface with the Raspberry Pi
#    and PiXi-200 hardware
#    Copyright (C) 2013 Simon Cantrill
#
#    pixi-tools is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


from sys import argv, stdin, stdout
from os.path import basename

# Crude script to do shell-like replacement with file content.
# Filter from stdin to stdout
# For each filename listed, such as dir/value.some-ext,
# replace ${VALUE} in input text with content of dir/value.some-ext

substs = []
for fname in argv[1:]:
        replace = open (fname).read()
        name = basename (fname)
        dot = name.find ('.')
        if dot > 0:
                name = name[:dot]
        find = '${' + name.upper() + '}'
        substs.append ((find, replace))

for line in stdin:
        for find, replace in substs:
                line = line.replace (find, replace)
        stdout.write (line)
